### ISSUE TITLE
DLM - Define metadata for each logging run

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/data-logging-module#2]

**Comment by hocally** [comment]
Adding @jrajan15 and @lealal here, they can provide some guidance on what they are going to log trackside. Obviously slightly different kinds of "metadata" but still probably a good idea to touch base.

**Comment by caljay98** [comment]
Use RTC to set a time and date for start of run (epoch time)

**Comment by caljay98** [comment]
No metadata, the unix epoch time will be the filename (for rev1 at least)
