### ISSUE TITLE
Explore external oscillators

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/data-logging-module#20]
Right now the dev board uses an external oscillator from the USB. Actual hardware will not have that

**Comment by caljay98** [comment]
This may not be needed, explore the clock setup page on CubeIDE

**Comment by caljay98** [comment]
Not needed, there is a 16MHz internal oscillator that will work just fine

**Comment by hocally** [comment]
Is this the main oscilator? It can only go up to 16 MHz? I think that's slower than the F0's on-chip clock
