### ISSUE TITLE
Interface with vehicle telemetry

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/data-logging-module#8]
Talk with VTM people to finalize communication between DLM and VTM

**Comment by hocally** [comment]
@caljay98 @jython234 If we end up going with XBees (seems sort of likely at this point), there are both SPI and UART APIs for bidirectional data transfer
[90002002.pdf](https://github.com/gopher-motorsports/data-logging-module/files/5791891/90002002.pdf)
