### ISSUE TITLE
Begin and end logging sessions

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/data-logging-module#9]
Add functionality to break up a drive day into multiple logging sessions by storing each in separate files

**Comment by hocally** [comment]
@caljay98 As far as functional requirements, I think we would need to ensure logging sessions can persist between boot cycles

**Comment by hocally** [comment]
I feel like we should write some specs for this

**Comment by caljay98** [comment]
Probably just log any time the car is running

**Comment by caljay98** [comment]
Good resources for the future:
https://controllerstech.com/stm32-ethernet-1-connection/
https://community.st.com/s/question/0D50X0000AhNBoWSQW/actually-working-stm32-ethernet-and-lwip-demonstration-firmware

**Comment by caljay98** [comment]
Make sure the entire life cycle of the DLM is well defined

**Comment by caljay98** [comment]
Power cycle is fine honestly
